# Generated by Django 4.0.4 on 2022-06-27 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newdjangoProject', '0002_topic_category_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20, null=True)),
                ('orders', models.ManyToManyField(to='newdjangoProject.order')),
            ],
        ),
    ]
