# Generated by Django 4.0.4 on 2022-07-04 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newdjangoProject', '0004_tag_student_tag_topic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interested', models.CharField(max_length=200)),
                ('levels', models.IntegerField(default=1)),
                ('comments', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
