# Generated by Django 4.0.4 on 2022-07-04 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newdjangoProject', '0005_interest'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='interested',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='stages',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
