# Generated by Django 4.0.4 on 2022-08-10 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newdjangoProject', '0007_student_avatar_alter_course_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='avatar',
            field=models.ImageField(upload_to='students'),
        ),
    ]
