# Generated by Django 4.0.4 on 2022-08-10 19:10

from django.db import migrations, models
import newdjangoProject.models


class Migration(migrations.Migration):

    dependencies = [
        ('newdjangoProject', '0008_alter_student_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='avatar',
            field=models.ImageField(upload_to=newdjangoProject.models.directory_path),
        ),
    ]
